export default [
		`Your grandmother's name`,
		`Your grandfather's name`,
		`Your current name`,
		`Your pet's name.`,
		`Your father's birthday`,
		`Your mother's birthday`,
		`What's your favorite food?`,
		`What are your lucky Numbers?`,
		`What is your dream job?`,
		`What's your favorite color?`,
		`What is your favorite sport?`,
		`What's your favorite book?`,
		`The name of the hospital where you were born？`,
		`What's your best friend's name?`,
		`What's your first company name?`,
		`Your favorite city`,
		`Your husband/wife's name`,
		`Your husband/wife's birthday`,
		`Your hometown`,
]